#ifndef __S2_DMPS_300_TEXT_ROUTERV0_8_H__
#define __S2_DMPS_300_TEXT_ROUTERV0_8_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_DMPS_300_Text_RouterV0_8_UP_DIG_INPUT 0
#define __S2_DMPS_300_Text_RouterV0_8_DOWN_DIG_INPUT 1
#define __S2_DMPS_300_Text_RouterV0_8_ROUTEBTN_DIG_INPUT 2
#define __S2_DMPS_300_Text_RouterV0_8_VIEWBTN_DIG_INPUT 3
#define __S2_DMPS_300_Text_RouterV0_8_INFOBTN_DIG_INPUT 4
#define __S2_DMPS_300_Text_RouterV0_8_SYSPWRBTN_DIG_INPUT 5
#define __S2_DMPS_300_Text_RouterV0_8_SYSTEMPOWERSTATE_DIG_INPUT 6
#define __S2_DMPS_300_Text_RouterV0_8_SYSTEMREADY_DIG_INPUT 7
#define __S2_DMPS_300_Text_RouterV0_8_MODE_INSTALLER_NOT_ACTIVE_DIG_INPUT 8

#define __S2_DMPS_300_Text_RouterV0_8_INPUT_DIGITALVIDEODETECTED_DIG_INPUT 9
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_DIGITALVIDEODETECTED_ARRAY_LENGTH 7
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_VGAVIDEODETECTED_DIG_INPUT 16
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_VGAVIDEODETECTED_ARRAY_LENGTH 3
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_BNCVIDEODETECTED_DIG_INPUT 19
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_BNCVIDEODETECTED_ARRAY_LENGTH 1

/*
* ANALOG_INPUT
*/
#define __S2_DMPS_300_Text_RouterV0_8_DESTINATIONSELECTED_ANALOG_INPUT 0
#define __S2_DMPS_300_Text_RouterV0_8_VIEWMODEDESTINATION_ANALOG_INPUT 1
#define __S2_DMPS_300_Text_RouterV0_8_SELECTEDINOUT_ANALOG_INPUT 2



#define __S2_DMPS_300_Text_RouterV0_8_VIDEOINPUT_ANALOG_INPUT 3
#define __S2_DMPS_300_Text_RouterV0_8_VIDEOINPUT_ARRAY_LENGTH 7
#define __S2_DMPS_300_Text_RouterV0_8_AUDIOINPUT_ANALOG_INPUT 10
#define __S2_DMPS_300_Text_RouterV0_8_AUDIOINPUT_ARRAY_LENGTH 7
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_HDMIVERTICALRESOLUTION_ANALOG_INPUT 17
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_HDMIVERTICALRESOLUTION_ARRAY_LENGTH 7
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_HDMIHORIZONTALRESOLUTION_ANALOG_INPUT 24
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_HDMIHORIZONTALRESOLUTION_ARRAY_LENGTH 7
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_HDMIREFRESHRATE_ANALOG_INPUT 31
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_HDMIREFRESHRATE_ARRAY_LENGTH 7
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_HDCPENABLED_ANALOG_INPUT 38
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_HDCPENABLED_ARRAY_LENGTH 7
#define __S2_DMPS_300_Text_RouterV0_8_OUTPUT_HDCPENABLED_ANALOG_INPUT 45
#define __S2_DMPS_300_Text_RouterV0_8_OUTPUT_HDCPENABLED_ARRAY_LENGTH 7
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_VGAVERTICALRESOLUTION_ANALOG_INPUT 52
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_VGAVERTICALRESOLUTION_ARRAY_LENGTH 3
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_VGAHORIZONTALRESOLUTION_ANALOG_INPUT 55
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_VGAHORIZONTALRESOLUTION_ARRAY_LENGTH 3
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_VGAREFRESHRATE_ANALOG_INPUT 58
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_VGAREFRESHRATE_ARRAY_LENGTH 3
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_BNCVERTICALRESOLUTION_ANALOG_INPUT 61
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_BNCVERTICALRESOLUTION_ARRAY_LENGTH 1
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_BNCHORIZONTALRESOLUTION_ANALOG_INPUT 62
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_BNCHORIZONTALRESOLUTION_ARRAY_LENGTH 1
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_BNCREFRESHRATE_ANALOG_INPUT 63
#define __S2_DMPS_300_Text_RouterV0_8_INPUT_BNCREFRESHRATE_ARRAY_LENGTH 1
#define __S2_DMPS_300_Text_RouterV0_8_SOURCENAMEIN$_STRING_INPUT 64
#define __S2_DMPS_300_Text_RouterV0_8_SOURCENAMEIN$_ARRAY_NUM_ELEMS 7
#define __S2_DMPS_300_Text_RouterV0_8_SOURCENAMEIN$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_DMPS_300_Text_RouterV0_8, __SOURCENAMEIN$, __S2_DMPS_300_Text_RouterV0_8_SOURCENAMEIN$_ARRAY_NUM_ELEMS, __S2_DMPS_300_Text_RouterV0_8_SOURCENAMEIN$_ARRAY_NUM_CHARS );
#define __S2_DMPS_300_Text_RouterV0_8_DESTINATIONNAMEIN$_STRING_INPUT 71
#define __S2_DMPS_300_Text_RouterV0_8_DESTINATIONNAMEIN$_ARRAY_NUM_ELEMS 7
#define __S2_DMPS_300_Text_RouterV0_8_DESTINATIONNAMEIN$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_DMPS_300_Text_RouterV0_8, __DESTINATIONNAMEIN$, __S2_DMPS_300_Text_RouterV0_8_DESTINATIONNAMEIN$_ARRAY_NUM_ELEMS, __S2_DMPS_300_Text_RouterV0_8_DESTINATIONNAMEIN$_ARRAY_NUM_CHARS );
#define __S2_DMPS_300_Text_RouterV0_8_MANF_STRING_STRING_INPUT 78
#define __S2_DMPS_300_Text_RouterV0_8_MANF_STRING_ARRAY_NUM_ELEMS 4
#define __S2_DMPS_300_Text_RouterV0_8_MANF_STRING_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_DMPS_300_Text_RouterV0_8, __MANF_STRING, __S2_DMPS_300_Text_RouterV0_8_MANF_STRING_ARRAY_NUM_ELEMS, __S2_DMPS_300_Text_RouterV0_8_MANF_STRING_ARRAY_NUM_CHARS );
#define __S2_DMPS_300_Text_RouterV0_8_NAME_STRING_STRING_INPUT 82
#define __S2_DMPS_300_Text_RouterV0_8_NAME_STRING_ARRAY_NUM_ELEMS 4
#define __S2_DMPS_300_Text_RouterV0_8_NAME_STRING_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_DMPS_300_Text_RouterV0_8, __NAME_STRING, __S2_DMPS_300_Text_RouterV0_8_NAME_STRING_ARRAY_NUM_ELEMS, __S2_DMPS_300_Text_RouterV0_8_NAME_STRING_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/


/*
* ANALOG_OUTPUT
*/
#define __S2_DMPS_300_Text_RouterV0_8_FRONTPANELMODE_ANALOG_OUTPUT 0

#define __S2_DMPS_300_Text_RouterV0_8_LINE2SCROLLARROW$_STRING_OUTPUT 1

#define __S2_DMPS_300_Text_RouterV0_8_SERIALOUT$_STRING_OUTPUT 2
#define __S2_DMPS_300_Text_RouterV0_8_SERIALOUT$_ARRAY_LENGTH 2

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_DMPS_300_Text_RouterV0_8_HDMIDMMODE_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_DMPS_300_Text_RouterV0_8, __HDMIDMMODE, __S2_DMPS_300_Text_RouterV0_8_HDMIDMMODE_STRING_MAX_LEN );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_DMPS_300_Text_RouterV0_8 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __INPUT_DIGITALVIDEODETECTED );
   DECLARE_IO_ARRAY( __INPUT_VGAVIDEODETECTED );
   DECLARE_IO_ARRAY( __INPUT_BNCVIDEODETECTED );
   DECLARE_IO_ARRAY( __VIDEOINPUT );
   DECLARE_IO_ARRAY( __AUDIOINPUT );
   DECLARE_IO_ARRAY( __INPUT_HDMIVERTICALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_HDMIHORIZONTALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_HDMIREFRESHRATE );
   DECLARE_IO_ARRAY( __INPUT_HDCPENABLED );
   DECLARE_IO_ARRAY( __OUTPUT_HDCPENABLED );
   DECLARE_IO_ARRAY( __INPUT_VGAVERTICALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_VGAHORIZONTALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_VGAREFRESHRATE );
   DECLARE_IO_ARRAY( __INPUT_BNCVERTICALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_BNCHORIZONTALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_BNCREFRESHRATE );
   DECLARE_IO_ARRAY( __SERIALOUT$ );
   unsigned short __LINE2DISPLAY;
   unsigned short __VIEWMODELINE2DISPLAY;
   unsigned short __VIEWMODE;
   unsigned short __VIEWMODESELECTION;
   DECLARE_STRING_STRUCT( S2_DMPS_300_Text_RouterV0_8, __HDMIDMMODE );
   DECLARE_STRING_ARRAY( S2_DMPS_300_Text_RouterV0_8, __SOURCENAMEIN$ );
   DECLARE_STRING_ARRAY( S2_DMPS_300_Text_RouterV0_8, __DESTINATIONNAMEIN$ );
   DECLARE_STRING_ARRAY( S2_DMPS_300_Text_RouterV0_8, __MANF_STRING );
   DECLARE_STRING_ARRAY( S2_DMPS_300_Text_RouterV0_8, __NAME_STRING );
};

START_NVRAM_VAR_STRUCT( S2_DMPS_300_Text_RouterV0_8 )
{
};



#endif //__S2_DMPS_300_TEXT_ROUTERV0_8_H__

